### ISSUE TITLE
AttributeError: 'PointTool' object has no attribute 'sample'

### ISSUE THREAD

**Issue by 3nids** [mkondratyev85/raster_tracer#11]
on first try:

```python
Traceback (most recent call last):
  File "/Users/denis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/raster_tracer.py", line 282, in checkBoxColor_changed
    self.tool_identify.trace_color_changed(color)
  File "/Users/denis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool.py", line 62, in trace_color_changed
    r,g,b = self.sample
AttributeError: 'PointTool' object has no attribute 'sample'
```

**Comment by mkondratyev85** [comment]
I would like to get more information about this issue, so I could work out the problem.

**Comment by mkondratyev85** [comment]
Closed as no more information is provided and it could possible be related to issues #21 or #20
