### ISSUE TITLE
Can't get tracing to work

### ISSUE THREAD

**Issue by chrowe** [mkondratyev85/raster_tracer#31]
## Setup
- MacBook Air (M1m 2020)
- MacOS Big Sur Version 11.2.3
- QGIS 3.18.0-Zürich
- Raster Tracer 0.3.2
- Raster geotif layer (converted from png by  https://mygeodata.cloud/converter/png-to-geotiff )
- http://gvellut.github.io/FreehandRasterGeoreferencer/ to georeference the raster file

## To reproduce 
1. Seems to install fine, shows up in the Plugins menu and the toolbar.
2. When I select the plugin the panel shows up fine and my raster layer is selected automatically but I get...
```
WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
```
and
```
WARNING    Traceback (most recent call last):
              File "/Users/chrowe/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/raster_tracer.py", line 254, in run
              self.tool_identify.raster_layer_has_changed(self.dockwidget.mMapLayerComboBox.currentLayer())
              File "/Users/chrowe/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool.py", line 246, in raster_layer_has_changed
              get_whole_raster(self.rlayer,
              File "/Users/chrowe/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/utils.py", line 38, in get_whole_raster
              dx = layer.rasterUnitsPerPixelX()
             AttributeError: 'FreehandRasterGeoreferencerLayer' object has no attribute 'rasterUnitsPerPixelX'
```

3. Layer > Create Layer > New Temporary Scratch Layer (I also tried shapefile), toggle editing on, and select the layer.
4. When I try to trace a line I get...
```
WARNING    Traceback (most recent call last):
              File "/Users/chrowe/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool.py", line 492, in canvasReleaseEvent
              self.state.click_lmb(mouseEvent, vlayer)
              File "/Users/chrowe/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool_states.py", line 90, in click_lmb
              if super().click_lmb(mouseEvent, vlayer) is False:
              File "/Users/chrowe/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool_states.py", line 63, in click_lmb
              if self.pointtool.to_indexes is None:
             AttributeError: 'PointTool' object has no attribute 'to_indexes'
```

**Comment by beyondwatts** [comment]
Did you get thsi to work?

**Comment by mkondratyev85** [comment]
It seems like this issue has to do with the FreenahdRasterGeoreferencerLayer. Maybe it would help to export this layer to the normal geotiff and then try to work on this geotiff raster layer.

**Comment by chrowe** [comment]
Ya, that seems to have fixed the issue I was having.
