### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by NicolasCadieux** [mkondratyev85/raster_tracer#34]
Hi,
This is the crash report I keep getting.
Thanks!
Nicolas

2022-01-20T21:38:48     WARNING    Traceback (most recent call last):
              File "C:\Users/Nicolas/AppData/Roaming/QGIS/QGIS3\profiles\Nico/python/plugins\raster_tracer\pointtool.py", line 492, in canvasReleaseEvent
              self.state.click_lmb(mouseEvent, vlayer)
              File "C:\Users/Nicolas/AppData/Roaming/QGIS/QGIS3\profiles\Nico/python/plugins\raster_tracer\pointtool_states.py", line 90, in click_lmb
              if super().click_lmb(mouseEvent, vlayer) is False:
              File "C:\Users/Nicolas/AppData/Roaming/QGIS/QGIS3\profiles\Nico/python/plugins\raster_tracer\pointtool_states.py", line 74, in click_lmb
              i1, j1 = self.pointtool.to_indexes(x1, y1)
              File "C:\Users/Nicolas/AppData/Roaming/QGIS/QGIS3\profiles\Nico/python/plugins\raster_tracer\utils.py", line 47, in 
              trfm_to_src.transform(x, y))
             Exception: unknown

**Comment by mkondratyev85** [comment]
Hi Nicolas. Thank you for the report! It looks like the problem is has to do with the projection of your raster layer. Could you specify the project CRS and layer CRS?

**Comment by NicolasCadieux** [comment]
Hi,
The project was in 2960 or 2948. The layer in 2949.  The files are in Byte - Eight bit unsigned integer with values of 1 or 0.  I did translate the files to  int16 if I recall.
Hope this helps!
Nicolas
